In [18]:
import pandas as pd
import os
import numpy as np

In [55]:
partial_folder = 'C:/Users/vitor/Desktop/Education/PET/Monografia/Dados/parciais/'
df=pd.DataFrame()

t_abs = 0

for i in os.listdir(partial_folder):
    dfp = pd.read_excel(partial_folder + i)
    df = pd.concat([df,dfp])
    print(i)
    t_abs += len(dfp['Abstract'].dropna())
    print(len(dfp['Abstract'].dropna()))

print(t_abs)
df.to_excel('journals.xls')

savedrecs (1).xls
988
savedrecs (10).xls
984
savedrecs (11).xls
983
savedrecs (12).xls
989
savedrecs (13).xls
982
savedrecs (14).xls
990
savedrecs (15).xls
979
savedrecs (16).xls
984
savedrecs (17).xls
982
savedrecs (18).xls
984
savedrecs (19).xls
969
savedrecs (2).xls
989
savedrecs (20).xls
979
savedrecs (21).xls
976
savedrecs (22).xls
978
savedrecs (23).xls
969
savedrecs (24).xls
972
savedrecs (25).xls
975
savedrecs (26).xls
962
savedrecs (27).xls
970
savedrecs (28).xls
965
savedrecs (29).xls
957
savedrecs (3).xls
984
savedrecs (30).xls
981
savedrecs (31).xls
979
savedrecs (32).xls
969
savedrecs (33).xls
978
savedrecs (34).xls
974
savedrecs (35).xls
962
savedrecs (36).xls
962
savedrecs (37).xls
966
savedrecs (38).xls
950
savedrecs (39).xls
985
savedrecs (4).xls
983
savedrecs (40).xls
959
savedrecs (41).xls
923
savedrecs (42).xls
962
savedrecs (43).xls
941
savedrecs (44).xls
946
savedrecs (45).xls
966
savedrecs (46).xls
957
savedrecs (47).xls
954
savedrecs (48).xls
940
savedrecs (49).xls
916
savedrecs (5).xls
997
savedrecs (50).xls
913
savedrecs (51).xls
940
savedrecs (52).xls
945
savedrecs (53).xls
926
savedrecs (54).xls
944
savedrecs (55).xls
948
savedrecs (56).xls
611
savedrecs (57).xls
2
savedrecs (58).xls
0
savedrecs (59).xls
0
savedrecs (6).xls
993
savedrecs (7).xls
995
savedrecs (8).xls
997
savedrecs (9).xls
986
savedrecs.xls
1000
54840

In [34]:
i = 1
df = pd.read_excel(partial_folder + os.listdir(partial_folder)[i])
print(len(df['Abstract'].dropna()))
#df.iloc[np.where(df['Abstract'].isna())]

984

,Publication Type,Authors,Book Authors,Book Editors,Book Group Authors,Author Full Names,Book Author Full Names,Group Authors,Article Title,Source Title,...,Web of Science Index,Research Areas,IDS Number,Pubmed Id,Open Access Designations,Highly Cited Status,Hot Paper Status,Date of Export,UT (Unique WOS ID),Web of Science Record
27,J,"Xiao, J; Kroeger, T; Khatib, O",NaN,NaN,NaN,"Xiao, Jing; Kroeger, Torsten; Khatib, Oussama",NaN,NaN,ISER 2018 Editorial,INTERNATIONAL JOURNAL OF ROBOTICS RESEARCH,...,Science Citation Index Expanded (SCI-EXPANDED),Robotics,NX6SC,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000575837500001,0
152,J,"Abbass, H",NaN,NaN,NaN,"Abbass, Hussein",NaN,NaN,Interview with Founding Editor-in-Chief of IEE...,IEEE COMPUTATIONAL INTELLIGENCE MAGAZINE,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,ML2QL,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000549316900001,0
264,J,"Xue, JH; Ma, ZY; Roveri, M; Japkowicz, N",NaN,NaN,NaN,"Xue, Jing-Hao; Ma, Zhanyu; Roveri, Manuel; Jap...",NaN,NaN,"Special Issue on Recent Advances in Theory, Me...",IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering,MW9QM,NaN,"Green Submitted, Bronze",NaN,NaN,2022-07-20,WOS:000557365700001,0
357,J,"Togacar, M; Comert, Z; Ergen, B; Ozyurt, F",NaN,NaN,NaN,"Togacar, Mesut; Comert, Zafer; Ergen, Burhan; ...",NaN,NaN,Classification of brain MRI using hyper column...,EXPERT SYSTEMS WITH APPLICATIONS,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering; Operations Rese...,LG6FG,NaN,NaN,NaN,NaN,2022-07-20,WOS:000528193700011,0
371,J,"Liu, L; Pietikainen, M; Qin, J; Ouyang, WL; Va...",NaN,NaN,NaN,"Liu, Li; Pietikainen, Matti; Qin, Jie; Ouyang,...",NaN,NaN,Efficient Visual Recognition,INTERNATIONAL JOURNAL OF COMPUTER VISION,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,MZ8HG,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000546900900001,0
402,J,"Chakrabarti, A; Sunkavalli, K; Forsyth, DA",NaN,NaN,NaN,"Chakrabarti, Ayan; Sunkavalli, Kalyan; Forsyth...",NaN,NaN,Guest Editors' Introduction to the Special Sec...,IEEE TRANSACTIONS ON PATTERN ANALYSIS AND MACH...,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering,MC0DH,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000542967200001,0
426,J,"Flach, PA",NaN,NaN,NaN,"Flach, Peter A.",NaN,NaN,Reflections on reciprocity in research,MACHINE LEARNING,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,ML6TT,32834470.0,"Bronze, Green Published",NaN,NaN,2022-07-20,WOS:000549596600001,0
555,J,"Kazakov, D; Aelezny, F",NaN,NaN,NaN,"Kazakov, Dimitar; Zelezny, Filip",NaN,NaN,Guest editors' introduction: special issue on ...,MACHINE LEARNING,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,ML6TT,NaN,"Green Published, Bronze",NaN,NaN,2022-07-20,WOS:000544939600001,0
619,J,"Kida, T; Kuboyama, T; Uno, T; Yamamoto, A",NaN,NaN,NaN,"Kida, Takuya; Kuboyama, Tetsuji; Uno, Takeaki;...",NaN,NaN,Guest Editorial: Special issue on Discovery Sc...,MACHINE LEARNING,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,MB1CR,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000539375700001,0
626,J,"Sechidis, K; Azzimonti, L; Pocock, A; Corani, ...",NaN,NaN,NaN,"Sechidis, Konstantinos; Azzimonti, Laura; Poco...",NaN,NaN,Efficient feature selection using shrinkage es...,MACHINE LEARNING,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,ND8BD,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000537956800001,0
750,J,"Sahin, GG",NaN,NaN,NaN,"Sahin, Gozde Gul",NaN,NaN,Linguistic Fundamentals for Natural Language P...,COMPUTATIONAL LINGUISTICS,...,Science Citation Index Expanded (SCI-EXPANDED)...,Computer Science; Linguistics,ME9JR,NaN,gold,NaN,NaN,2022-07-20,WOS:000544970400009,0
828,J,"Miller-Jackson, T; Sun, Y; Natividad, R; Yeow, CH",NaN,NaN,NaN,"Miller-Jackson, T.; Sun, Y.; Natividad, R.; Ye...",NaN,NaN,Tubular Jamming: A Variable Stiffening Method ...,SOFT ROBOTICS,...,Science Citation Index Expanded (SCI-EXPANDED),Robotics,LU3ZX,NaN,Green Published,NaN,NaN,2022-07-20,WOS:000535447300001,0
840,J,"Benitez-Buenache, A; Alvarez-Perez, L; Mathews...",NaN,NaN,NaN,"Benitez-Buenache, Alexander; Alvarez-Perez, Lo...",NaN,NaN,Likelihood ratio equivalence and imbalanced bi...,EXPERT SYSTEMS WITH APPLICATIONS,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering; Operations Rese...,KU4AX,NaN,NaN,NaN,NaN,2022-07-20,WOS:000519653400014,0
871,J,"Kiran, M; Khan, S",NaN,NaN,NaN,"Kiran, Mariam; Khan, Samir",NaN,NaN,Editorial: Machine learning for safety-critica...,MACHINE LEARNING,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,LQ2AA,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000530772900001,0
893,J,"Escalera, S; Escalante, HJ; Baro, X; Guyon, I;...",NaN,NaN,NaN,"Escalera, Sergio; Escalante, Hugo Jair; Baro, ...",NaN,NaN,Guest Editorial: Image and Video Inpainting an...,IEEE TRANSACTIONS ON PATTERN ANALYSIS AND MACH...,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering,LA0ZT,NaN,"Bronze, Green Submitted",NaN,NaN,2022-07-20,WOS:000523685800001,0
901,J,"Gong, MG; Xie, Y; Pan, K; Feng, KY; Qin, AK",NaN,NaN,NaN,"Gong, Maoguo; Xie, Yu; Pan, Ke; Feng, Kaiyuan;...",NaN,NaN,A Survey on Differentially Private Machine Lea...,IEEE COMPUTATIONAL INTELLIGENCE MAGAZINE,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,PU4HF,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000609267000004,0

In [32]:
df.iloc[np.where(df['Abstract'].isna())]

,Publication Type,Authors,Book Authors,Book Editors,Book Group Authors,Author Full Names,Book Author Full Names,Group Authors,Article Title,Source Title,...,Web of Science Index,Research Areas,IDS Number,Pubmed Id,Open Access Designations,Highly Cited Status,Hot Paper Status,Date of Export,UT (Unique WOS ID),Web of Science Record
46,J,"Gammerman, A; Vovk, V; Cristani, M",NaN,NaN,NaN,"Gammerman, Alexander; Vovk, Vladimir; Cristani...",NaN,NaN,Special Issue on Conformal and Probabilistic P...,PATTERN RECOGNITION,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering,ZH7XW,NaN,NaN,NaN,NaN,2022-07-20,WOS:000761147800005,0
103,J,"Pang, GS; Aggarwal, C; Shen, CH; Sebe, N",NaN,NaN,NaN,"Pang, Guansong; Aggarwal, Charu; Shen, Chunhua...",NaN,NaN,Deep Learning for Anomaly Detection,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering,1T4KK,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000804699400005,0
134,J,"TANAKA, G; GALLICCHIO, C; MICHELI, A; ORTEGA, ...",NaN,NaN,NaN,"TANAKA, G. O. U. H. E., I; GALLICCHIO, C. L. A...",NaN,NaN,Special Issue on New Frontiers in Extremely Ef...,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering,1T4KK,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000804699400028,0
294,J,"Patsantzis, S; Muggleton, SH",NaN,NaN,NaN,"Patsantzis, S.; Muggleton, S. H.",NaN,NaN,Meta-interpretive learning as metarule special...,MACHINE LEARNING,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,1H1NJ,NaN,hybrid,NaN,NaN,2022-07-20,WOS:000796313500002,0
393,J,"Yang, X; Yan, JC",NaN,NaN,NaN,"Yang, Xue; Yan, Junchi",NaN,NaN,On the Arbitrary-Oriented Object Detection: Cl...,INTERNATIONAL JOURNAL OF COMPUTER VISION,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,2M4VH,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000791670100001,0
476,J,"Jiang, YX; Wu, Q; Zhu, SK; Zhang, LK",NaN,NaN,NaN,"Jiang, Yuxin; Wu, Qing; Zhu, Shenke; Zhang, Luke",NaN,NaN,Orca predation algorithm: A novel bio-inspired...,EXPERT SYSTEMS WITH APPLICATIONS,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering; Operations Rese...,1M9GW,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000800274500012,0
483,J,"Keller, J",NaN,NaN,NaN,"Keller, Jim",NaN,NaN,What's Cooking in CIS?,IEEE COMPUTATIONAL INTELLIGENCE MAGAZINE,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,1C1TT,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000792910900006,0
550,J,"Song, YD; Si, J; Coleman, S; Kerr, D",NaN,NaN,NaN,"Song, Yongduan; Si, Jennie; Coleman, Sonya; Ke...",NaN,NaN,Biologically Learned/Inspired Methods for Sens...,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering,0Z1DB,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000790819200005,0
555,J,"Ting, CK",NaN,NaN,NaN,"Ting, Chuan-Kang",NaN,NaN,Digging Deeper Into the Stories,IEEE COMPUTATIONAL INTELLIGENCE MAGAZINE,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,1C1TT,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000792910900003,0
701,J,"Xiao, TH; Liu, SF; De Mello, S; Yu, ZD; Kautz,...",NaN,NaN,NaN,"Xiao, Taihong; Liu, Sifei; De Mello, Shalini; ...",NaN,NaN,Learning Contrastive Representation for Semant...,INTERNATIONAL JOURNAL OF COMPUTER VISION,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,1N7TU,NaN,Bronze,NaN,NaN,2022-07-20,WOS:000783447900001,0
749,J,"Caraffini, F; Chiclana, F; Moodley, R; Gongora, M",NaN,NaN,NaN,"Caraffini, Fabio; Chiclana, Francisco; Moodley...",NaN,NaN,Applications of computational intelligence-bas...,INTERNATIONAL JOURNAL OF INTELLIGENT SYSTEMS,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,ZI6XJ,NaN,NaN,NaN,NaN,2022-07-20,WOS:000761761600003,0
978,J,"Wang, M; Zhang, C; Hao, SJ; Yu, J; Mu, TT",NaN,NaN,NaN,"Wang, Meng; Zhang, Chi; Hao, Shijie; Yu, Jun; ...",NaN,NaN,Guest Editorial: Intelligent information proce...,INTERNATIONAL JOURNAL OF INTELLIGENT SYSTEMS,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science,ZY7DX,NaN,NaN,NaN,NaN,2022-07-20,WOS:000769983300001,0

In [51]:
df.iloc[np.where(df['Date of Export'].value_counts() > 1)]

,Publication Type,Authors,Book Authors,Book Editors,Book Group Authors,Author Full Names,Book Author Full Names,Group Authors,Article Title,Source Title,...,Web of Science Index,Research Areas,IDS Number,Pubmed Id,Open Access Designations,Highly Cited Status,Hot Paper Status,Date of Export,UT (Unique WOS ID),Web of Science Record
0,J,"Liu, JY; Zhang, JG; Wang, YC",NaN,NaN,NaN,"Liu, Jiayue; Zhang, Jianguo; Wang, Yuncai",NaN,NaN,Secure Communication via Chaotic Synchronizati...,IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARN...,...,Science Citation Index Expanded (SCI-EXPANDED),Computer Science; Engineering,2A2XU,35653446.0,NaN,NaN,NaN,2022-07-20,WOS:000809371300001,0

In [52]:
np.where(df['Date of Export'].value_counts() > 1)

(array([0], dtype=int64),)

In [60]:
max(df['Publication Year'].value_counts().index)

2022.0

In [58]:
df['Publication Year'].value_counts().index

Float64Index([2021.0, 2020.0, 2022.0, 2012.0, 2011.0, 2018.0, 2019.0, 2009.0,
              2015.0, 2017.0, 2016.0, 2010.0, 2014.0, 2013.0, 2008.0, 2007.0,
              2006.0, 2005.0, 2004.0, 2003.0, 2002.0, 2001.0, 1998.0, 1996.0,
              1999.0, 1997.0, 2000.0, 1995.0, 1992.0, 1994.0, 1993.0, 1991.0,
              1990.0, 1989.0, 1988.0, 1987.0, 1984.0, 1986.0, 1981.0, 1983.0,
              1985.0, 1982.0, 1980.0, 1979.0, 1978.0, 1976.0, 1971.0, 1973.0,
              1972.0, 1977.0, 1975.0, 1970.0, 1974.0, 1969.0, 1968.0],
             dtype='float64')